from .base import *

"""
Django settings for intra_musical_site project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

DEBUG = True

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "intramusical",
        "USER": "intramusical_user",
        "PASSWORD": "intramusicalpassword",
        "HOST": "localhost",
        "PORT": "5432"
    }
}
